"""Appointment scheduling module tables."""

from alembic import op
import sqlalchemy as sa

revision = "0023_appointments"
down_revision = "0022_message_gestures"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table("appointments_settings", sa.Column("id", sa.Uuid(), primary_key=True), sa.Column("client_id", sa.Uuid(), sa.ForeignKey("clients.id", ondelete="CASCADE"), nullable=False, unique=True), sa.Column("enabled", sa.Boolean(), server_default=sa.false(), nullable=False), sa.Column("timezone", sa.String(64), server_default="UTC", nullable=False), sa.Column("min_notice_minutes", sa.Integer(), server_default="60", nullable=False), sa.Column("max_advance_days", sa.Integer(), server_default="90", nullable=False), sa.Column("cancellation_notice_minutes", sa.Integer(), server_default="120", nullable=False), sa.Column("reschedule_notice_minutes", sa.Integer(), server_default="120", nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False))
    op.create_table("appointments_locations", sa.Column("id", sa.Uuid(), primary_key=True), sa.Column("client_id", sa.Uuid(), sa.ForeignKey("clients.id", ondelete="CASCADE"), nullable=False), sa.Column("name", sa.String(180), nullable=False), sa.Column("address", sa.Text(), server_default="", nullable=False), sa.Column("timezone", sa.String(64), server_default="UTC", nullable=False), sa.Column("is_active", sa.Boolean(), server_default=sa.true(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False))
    op.create_table("appointments_professionals", sa.Column("id", sa.Uuid(), primary_key=True), sa.Column("client_id", sa.Uuid(), sa.ForeignKey("clients.id", ondelete="CASCADE"), nullable=False), sa.Column("name", sa.String(180), nullable=False), sa.Column("email", sa.String(320), server_default="", nullable=False), sa.Column("phone", sa.String(80), server_default="", nullable=False), sa.Column("is_active", sa.Boolean(), server_default=sa.true(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False))
    op.create_table("appointments_services", sa.Column("id", sa.Uuid(), primary_key=True), sa.Column("client_id", sa.Uuid(), sa.ForeignKey("clients.id", ondelete="CASCADE"), nullable=False), sa.Column("name", sa.String(180), nullable=False), sa.Column("description", sa.Text(), server_default="", nullable=False), sa.Column("duration_minutes", sa.Integer(), server_default="60", nullable=False), sa.Column("buffer_before_minutes", sa.Integer(), server_default="0", nullable=False), sa.Column("buffer_after_minutes", sa.Integer(), server_default="0", nullable=False), sa.Column("is_active", sa.Boolean(), server_default=sa.true(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False))
    op.create_table("appointments_professional_locations", sa.Column("id", sa.Uuid(), primary_key=True), sa.Column("professional_id", sa.Uuid(), sa.ForeignKey("appointments_professionals.id", ondelete="CASCADE"), nullable=False), sa.Column("location_id", sa.Uuid(), sa.ForeignKey("appointments_locations.id", ondelete="CASCADE"), nullable=False), sa.UniqueConstraint("professional_id", "location_id", name="uq_appointments_professional_location"))
    op.create_table("appointments_professional_services", sa.Column("id", sa.Uuid(), primary_key=True), sa.Column("professional_id", sa.Uuid(), sa.ForeignKey("appointments_professionals.id", ondelete="CASCADE"), nullable=False), sa.Column("service_id", sa.Uuid(), sa.ForeignKey("appointments_services.id", ondelete="CASCADE"), nullable=False), sa.Column("location_id", sa.Uuid(), sa.ForeignKey("appointments_locations.id", ondelete="CASCADE"), nullable=False), sa.UniqueConstraint("professional_id", "service_id", "location_id", name="uq_appointments_professional_service_location"))
    op.create_table("appointments_schedules", sa.Column("id", sa.Uuid(), primary_key=True), sa.Column("professional_id", sa.Uuid(), sa.ForeignKey("appointments_professionals.id", ondelete="CASCADE"), nullable=False), sa.Column("location_id", sa.Uuid(), sa.ForeignKey("appointments_locations.id", ondelete="CASCADE"), nullable=False), sa.Column("weekday", sa.Integer(), nullable=False), sa.Column("start_time", sa.Time(), nullable=False), sa.Column("end_time", sa.Time(), nullable=False), sa.UniqueConstraint("professional_id", "location_id", "weekday", "start_time", name="uq_appointments_schedule_start"))
    op.create_table("appointments_time_off", sa.Column("id", sa.Uuid(), primary_key=True), sa.Column("professional_id", sa.Uuid(), sa.ForeignKey("appointments_professionals.id", ondelete="CASCADE"), nullable=False), sa.Column("location_id", sa.Uuid(), sa.ForeignKey("appointments_locations.id", ondelete="CASCADE"), nullable=True), sa.Column("kind", sa.String(20), server_default="block", nullable=False), sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False), sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False), sa.Column("reason", sa.Text(), server_default="", nullable=False))
    op.create_table("appointments", sa.Column("id", sa.Uuid(), primary_key=True), sa.Column("client_id", sa.Uuid(), sa.ForeignKey("clients.id", ondelete="CASCADE"), nullable=False), sa.Column("location_id", sa.Uuid(), sa.ForeignKey("appointments_locations.id", ondelete="RESTRICT"), nullable=False), sa.Column("professional_id", sa.Uuid(), sa.ForeignKey("appointments_professionals.id", ondelete="RESTRICT"), nullable=False), sa.Column("service_id", sa.Uuid(), sa.ForeignKey("appointments_services.id", ondelete="RESTRICT"), nullable=False), sa.Column("customer_phone", sa.String(80), nullable=False), sa.Column("customer_name", sa.String(180), server_default="", nullable=False), sa.Column("customer_email", sa.String(320), server_default="", nullable=False), sa.Column("notes", sa.Text(), server_default="", nullable=False), sa.Column("source", sa.String(30), server_default="portal", nullable=False), sa.Column("status", sa.String(30), server_default="confirmed", nullable=False), sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False), sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False), sa.Column("external_id", sa.String(180), nullable=True), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("client_id", "external_id", name="uq_appointments_external_id"))
    for table, cols in {"appointments_locations":["client_id"],"appointments_professionals":["client_id"],"appointments_services":["client_id"],"appointments_professional_locations":["professional_id","location_id"],"appointments_professional_services":["professional_id","service_id","location_id"],"appointments_schedules":["professional_id","location_id"],"appointments_time_off":["professional_id","location_id"],"appointments":["client_id","location_id","professional_id","service_id","customer_phone","status","starts_at","ends_at"]}.items():
        for col in cols: op.create_index(f"ix_{table}_{col}", table, [col])


def downgrade() -> None:
    for table in ("appointments", "appointments_time_off", "appointments_schedules", "appointments_professional_services", "appointments_professional_locations", "appointments_services", "appointments_professionals", "appointments_locations", "appointments_settings"):
        op.drop_table(table)
